<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProvincesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('provinces', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('type');
            $table->bigInteger('matp')->unsigned();
            $table->foreign('matp')->references('id')->on('cities');
            // $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('provinces');
    }
}
// INSERT INTO `provinces` VALUES ('01', 'Quận Ba Đình', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('02', 'Quận Hoàn Kiếm', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('03', 'Quận Tây Hồ', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('04', 'Quận Long Biên', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('05', 'Quận Cầu Giấy', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('06', 'Quận Đống Đa', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('07', 'Quận Hai Bà Trưng', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('08', 'Quận Hoàng Mai', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('09', 'Quận Thanh Xuân', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('16', 'Huyện Sóc Sơn', 'Huyện', 1);
// INSERT INTO `provinces` VALUES ('17', 'Huyện Đông Anh', 'Huyện', 1);
// INSERT INTO `provinces` VALUES ('18', 'Huyện Gia Lâm', 'Huyện', 1);
// INSERT INTO `provinces` VALUES ('19', 'Quận Nam Từ Liêm', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('20', 'Huyện Thanh Trì', 'Huyện', 1);
// INSERT INTO `provinces` VALUES ('21', 'Quận Bắc Từ Liêm', 'Quận', 1);
// INSERT INTO `provinces` VALUES ('24', 'Thành phố Hà Giang', 'Thành phố', '2');
// INSERT INTO `provinces` VALUES ('26', 'Huyện Đồng Văn', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('27', 'Huyện Mèo Vạc', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('28', 'Huyện Yên Minh', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('29', 'Huyện Quản Bạ', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('30', 'Huyện Vị Xuyên', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('31', 'Huyện Bắc Mê', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('32', 'Huyện Hoàng Su Phì', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('33', 'Huyện Xín Mần', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('34', 'Huyện Bắc Quang', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('35', 'Huyện Quang Bình', 'Huyện', '2');
// INSERT INTO `provinces` VALUES ('40', 'Thành phố Cao Bằng', 'Thành phố', '4');
// INSERT INTO `provinces` VALUES ('42', 'Huyện Bảo Lâm', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('43', 'Huyện Bảo Lạc', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('44', 'Huyện Thông Nông', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('45', 'Huyện Hà Quảng', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('46', 'Huyện Trà Lĩnh', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('47', 'Huyện Trùng Khánh', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('48', 'Huyện Hạ Lang', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('49', 'Huyện Quảng Uyên', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('50', 'Huyện Phục Hoà', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('51', 'Huyện Hoà An', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('52', 'Huyện Nguyên Bình', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('53', 'Huyện Thạch An', 'Huyện', '4');
// INSERT INTO `provinces` VALUES ('58', 'Thành Phố Bắc Kạn', 'Thành phố', '6');
// INSERT INTO `provinces` VALUES ('60', 'Huyện Pác Nặm', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('61', 'Huyện Ba Bể', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('62', 'Huyện Ngân Sơn', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('63', 'Huyện Bạch Thông', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('64', 'Huyện Chợ Đồn', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('65', 'Huyện Chợ Mới', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('66', 'Huyện Na Rì', 'Huyện', '6');
// INSERT INTO `provinces` VALUES ('70', 'Thành phố Tuyên Quang', 'Thành phố', '8');
// INSERT INTO `provinces` VALUES ('71', 'Huyện Lâm Bình', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('72', 'Huyện Nà Hang', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('73', 'Huyện Chiêm Hóa', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('74', 'Huyện Hàm Yên', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('75', 'Huyện Yên Sơn', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('76', 'Huyện Sơn Dương', 'Huyện', '8');
// INSERT INTO `provinces` VALUES ('80', 'Thành phố Lào Cai', 'Thành phố', '10');
// INSERT INTO `provinces` VALUES ('82', 'Huyện Bát Xát', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('83', 'Huyện Mường Khương', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('84', 'Huyện Si Ma Cai', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('85', 'Huyện Bắc Hà', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('86', 'Huyện Bảo Thắng', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('87', 'Huyện Bảo Yên', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('88', 'Huyện Sa Pa', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('89', 'Huyện Văn Bàn', 'Huyện', '10');
// INSERT INTO `provinces` VALUES ('94', 'Thành phố Điện Biên Phủ', 'Thành phố', '11');
// INSERT INTO `provinces` VALUES ('95', 'Thị Xã Mường Lay', 'Thị xã', '11');
// INSERT INTO `provinces` VALUES ('96', 'Huyện Mường Nhé', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('97', 'Huyện Mường Chà', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('98', 'Huyện Tủa Chùa', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('99', 'Huyện Tuần Giáo', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('100', 'Huyện Điện Biên', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('101', 'Huyện Điện Biên Đông', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('102', 'Huyện Mường Ảng', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('103', 'Huyện Nậm Pồ', 'Huyện', '11');
// INSERT INTO `provinces` VALUES ('105', 'Thành phố Lai Châu', 'Thành phố', '12');
// INSERT INTO `provinces` VALUES ('106', 'Huyện Tam Đường', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('107', 'Huyện Mường Tè', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('108', 'Huyện Sìn Hồ', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('109', 'Huyện Phong Thổ', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('110', 'Huyện Than Uyên', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('111', 'Huyện Tân Uyên', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('112', 'Huyện Nậm Nhùn', 'Huyện', '12');
// INSERT INTO `provinces` VALUES ('116', 'Thành phố Sơn La', 'Thành phố', '14');
// INSERT INTO `provinces` VALUES ('118', 'Huyện Quỳnh Nhai', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('119', 'Huyện Thuận Châu', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('120', 'Huyện Mường La', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('121', 'Huyện Bắc Yên', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('122', 'Huyện Phù Yên', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('123', 'Huyện Mộc Châu', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('124', 'Huyện Yên Châu', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('125', 'Huyện Mai Sơn', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('126', 'Huyện Sông Mã', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('127', 'Huyện Sốp Cộp', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('128', 'Huyện Vân Hồ', 'Huyện', '14');
// INSERT INTO `provinces` VALUES ('132', 'Thành phố Yên Bái', 'Thành phố', '15');
// INSERT INTO `provinces` VALUES ('133', 'Thị xã Nghĩa Lộ', 'Thị xã', '15');
// INSERT INTO `provinces` VALUES ('135', 'Huyện Lục Yên', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('136', 'Huyện Văn Yên', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('137', 'Huyện Mù Căng Chải', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('138', 'Huyện Trấn Yên', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('139', 'Huyện Trạm Tấu', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('140', 'Huyện Văn Chấn', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('141', 'Huyện Yên Bình', 'Huyện', '15');
// INSERT INTO `provinces` VALUES ('148', 'Thành phố Hòa Bình', 'Thành phố', '17');
// INSERT INTO `provinces` VALUES ('150', 'Huyện Đà Bắc', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('151', 'Huyện Kỳ Sơn', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('152', 'Huyện Lương Sơn', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('153', 'Huyện Kim Bôi', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('154', 'Huyện Cao Phong', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('155', 'Huyện Tân Lạc', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('156', 'Huyện Mai Châu', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('157', 'Huyện Lạc Sơn', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('158', 'Huyện Yên Thủy', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('159', 'Huyện Lạc Thủy', 'Huyện', '17');
// INSERT INTO `provinces` VALUES ('164', 'Thành phố Thái Nguyên', 'Thành phố', '19');
// INSERT INTO `provinces` VALUES ('165', 'Thành phố Sông Công', 'Thành phố', '19');
// INSERT INTO `provinces` VALUES ('167', 'Huyện Định Hóa', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('168', 'Huyện Phú Lương', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('169', 'Huyện Đồng Hỷ', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('170', 'Huyện Võ Nhai', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('171', 'Huyện Đại Từ', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('172', 'Thị xã Phổ Yên', 'Thị xã', '19');
// INSERT INTO `provinces` VALUES ('173', 'Huyện Phú Bình', 'Huyện', '19');
// INSERT INTO `provinces` VALUES ('178', 'Thành phố Lạng Sơn', 'Thành phố', '20');
// INSERT INTO `provinces` VALUES ('180', 'Huyện Tràng Định', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('181', 'Huyện Bình Gia', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('182', 'Huyện Văn Lãng', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('183', 'Huyện Cao Lộc', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('184', 'Huyện Văn Quan', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('185', 'Huyện Bắc Sơn', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('186', 'Huyện Hữu Lũng', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('187', 'Huyện Chi Lăng', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('188', 'Huyện Lộc Bình', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('189', 'Huyện Đình Lập', 'Huyện', '20');
// INSERT INTO `provinces` VALUES ('193', 'Thành phố Hạ Long', 'Thành phố', '22');
// INSERT INTO `provinces` VALUES ('194', 'Thành phố Móng Cái', 'Thành phố', '22');
// INSERT INTO `provinces` VALUES ('195', 'Thành phố Cẩm Phả', 'Thành phố', '22');
// INSERT INTO `provinces` VALUES ('196', 'Thành phố Uông Bí', 'Thành phố', '22');
// INSERT INTO `provinces` VALUES ('198', 'Huyện Bình Liêu', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('199', 'Huyện Tiên Yên', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('200', 'Huyện Đầm Hà', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('201', 'Huyện Hải Hà', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('202', 'Huyện Ba Chẽ', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('203', 'Huyện Vân Đồn', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('204', 'Huyện Hoành Bồ', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('205', 'Thị xã Đông Triều', 'Thị xã', '22');
// INSERT INTO `provinces` VALUES ('206', 'Thị xã Quảng Yên', 'Thị xã', '22');
// INSERT INTO `provinces` VALUES ('207', 'Huyện Cô Tô', 'Huyện', '22');
// INSERT INTO `provinces` VALUES ('213', 'Thành phố Bắc Giang', 'Thành phố', '24');
// INSERT INTO `provinces` VALUES ('215', 'Huyện Yên Thế', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('216', 'Huyện Tân Yên', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('217', 'Huyện Lạng Giang', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('218', 'Huyện Lục Nam', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('219', 'Huyện Lục Ngạn', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('220', 'Huyện Sơn Động', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('221', 'Huyện Yên Dũng', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('222', 'Huyện Việt Yên', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('223', 'Huyện Hiệp Hòa', 'Huyện', '24');
// INSERT INTO `provinces` VALUES ('227', 'Thành phố Việt Trì', 'Thành phố', '25');
// INSERT INTO `provinces` VALUES ('228', 'Thị xã Phú Thọ', 'Thị xã', '25');
// INSERT INTO `provinces` VALUES ('230', 'Huyện Đoan Hùng', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('231', 'Huyện Hạ Hoà', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('232', 'Huyện Thanh Ba', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('233', 'Huyện Phù Ninh', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('234', 'Huyện Yên Lập', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('235', 'Huyện Cẩm Khê', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('236', 'Huyện Tam Nông', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('237', 'Huyện Lâm Thao', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('238', 'Huyện Thanh Sơn', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('239', 'Huyện Thanh Thuỷ', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('240', 'Huyện Tân Sơn', 'Huyện', '25');
// INSERT INTO `provinces` VALUES ('243', 'Thành phố Vĩnh Yên', 'Thành phố', '26');
// INSERT INTO `provinces` VALUES ('244', 'Thị xã Phúc Yên', 'Thị xã', '26');
// INSERT INTO `provinces` VALUES ('246', 'Huyện Lập Thạch', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('247', 'Huyện Tam Dương', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('248', 'Huyện Tam Đảo', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('249', 'Huyện Bình Xuyên', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('250', 'Huyện Mê Linh', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('251', 'Huyện Yên Lạc', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('252', 'Huyện Vĩnh Tường', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('253', 'Huyện Sông Lô', 'Huyện', '26');
// INSERT INTO `provinces` VALUES ('256', 'Thành phố Bắc Ninh', 'Thành phố', '27');
// INSERT INTO `provinces` VALUES ('258', 'Huyện Yên Phong', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('259', 'Huyện Quế Võ', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('260', 'Huyện Tiên Du', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('261', 'Thị xã Từ Sơn', 'Thị xã', '27');
// INSERT INTO `provinces` VALUES ('262', 'Huyện Thuận Thành', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('263', 'Huyện Gia Bình', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('264', 'Huyện Lương Tài', 'Huyện', '27');
// INSERT INTO `provinces` VALUES ('268', 'Quận Hà Đông', 'Quận', '1');
// INSERT INTO `provinces` VALUES ('269', 'Thị xã Sơn Tây', 'Thị xã', '1');
// INSERT INTO `provinces` VALUES ('271', 'Huyện Ba Vì', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('272', 'Huyện Phúc Thọ', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('273', 'Huyện Đan Phượng', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('274', 'Huyện Hoài Đức', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('275', 'Huyện Quốc Oai', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('276', 'Huyện Thạch Thất', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('277', 'Huyện Chương Mỹ', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('278', 'Huyện Thanh Oai', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('279', 'Huyện Thường Tín', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('280', 'Huyện Phú Xuyên', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('281', 'Huyện Ứng Hòa', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('282', 'Huyện Mỹ Đức', 'Huyện', '1');
// INSERT INTO `provinces` VALUES ('288', 'Thành phố Hải Dương', 'Thành phố', '30');
// INSERT INTO `provinces` VALUES ('290', 'Thị xã Chí Linh', 'Thị xã', '30');
// INSERT INTO `provinces` VALUES ('291', 'Huyện Nam Sách', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('292', 'Huyện Kinh Môn', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('293', 'Huyện Kim Thành', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('294', 'Huyện Thanh Hà', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('295', 'Huyện Cẩm Giàng', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('296', 'Huyện Bình Giang', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('297', 'Huyện Gia Lộc', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('298', 'Huyện Tứ Kỳ', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('299', 'Huyện Ninh Giang', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('300', 'Huyện Thanh Miện', 'Huyện', '30');
// INSERT INTO `provinces` VALUES ('303', 'Quận Hồng Bàng', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('304', 'Quận Ngô Quyền', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('305', 'Quận Lê Chân', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('306', 'Quận Hải An', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('307', 'Quận Kiến An', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('308', 'Quận Đồ Sơn', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('309', 'Quận Dương Kinh', 'Quận', '31');
// INSERT INTO `provinces` VALUES ('311', 'Huyện Thuỷ Nguyên', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('312', 'Huyện An Dương', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('313', 'Huyện An Lão', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('314', 'Huyện Kiến Thuỵ', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('315', 'Huyện Tiên Lãng', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('316', 'Huyện Vĩnh Bảo', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('317', 'Huyện Cát Hải', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('318', 'Huyện Bạch Long Vĩ', 'Huyện', '31');
// INSERT INTO `provinces` VALUES ('323', 'Thành phố Hưng Yên', 'Thành phố', '33');
// INSERT INTO `provinces` VALUES ('325', 'Huyện Văn Lâm', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('326', 'Huyện Văn Giang', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('327', 'Huyện Yên Mỹ', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('328', 'Huyện Mỹ Hào', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('329', 'Huyện Ân Thi', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('330', 'Huyện Khoái Châu', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('331', 'Huyện Kim Động', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('332', 'Huyện Tiên Lữ', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('333', 'Huyện Phù Cừ', 'Huyện', '33');
// INSERT INTO `provinces` VALUES ('336', 'Thành phố Thái Bình', 'Thành phố', '34');
// INSERT INTO `provinces` VALUES ('338', 'Huyện Quỳnh Phụ', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('339', 'Huyện Hưng Hà', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('340', 'Huyện Đông Hưng', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('341', 'Huyện Thái Thụy', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('342', 'Huyện Tiền Hải', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('343', 'Huyện Kiến Xương', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('344', 'Huyện Vũ Thư', 'Huyện', '34');
// INSERT INTO `provinces` VALUES ('347', 'Thành phố Phủ Lý', 'Thành phố', '35');
// INSERT INTO `provinces` VALUES ('349', 'Huyện Duy Tiên', 'Huyện', '35');
// INSERT INTO `provinces` VALUES ('350', 'Huyện Kim Bảng', 'Huyện', '35');
// INSERT INTO `provinces` VALUES ('351', 'Huyện Thanh Liêm', 'Huyện', '35');
// INSERT INTO `provinces` VALUES ('352', 'Huyện Bình Lục', 'Huyện', '35');
// INSERT INTO `provinces` VALUES ('353', 'Huyện Lý Nhân', 'Huyện', '35');
// INSERT INTO `provinces` VALUES ('356', 'Thành phố Nam Định', 'Thành phố', '36');
// INSERT INTO `provinces` VALUES ('358', 'Huyện Mỹ Lộc', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('359', 'Huyện Vụ Bản', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('360', 'Huyện Ý Yên', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('361', 'Huyện Nghĩa Hưng', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('362', 'Huyện Nam Trực', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('363', 'Huyện Trực Ninh', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('364', 'Huyện Xuân Trường', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('365', 'Huyện Giao Thủy', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('366', 'Huyện Hải Hậu', 'Huyện', '36');
// INSERT INTO `provinces` VALUES ('369', 'Thành phố Ninh Bình', 'Thành phố', '37');
// INSERT INTO `provinces` VALUES ('370', 'Thành phố Tam Điệp', 'Thành phố', '37');
// INSERT INTO `provinces` VALUES ('372', 'Huyện Nho Quan', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('373', 'Huyện Gia Viễn', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('374', 'Huyện Hoa Lư', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('375', 'Huyện Yên Khánh', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('376', 'Huyện Kim Sơn', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('377', 'Huyện Yên Mô', 'Huyện', '37');
// INSERT INTO `provinces` VALUES ('380', 'Thành phố Thanh Hóa', 'Thành phố', '38');
// INSERT INTO `provinces` VALUES ('381', 'Thị xã Bỉm Sơn', 'Thị xã', '38');
// INSERT INTO `provinces` VALUES ('382', 'Thị xã Sầm Sơn', 'Thị xã', '38');
// INSERT INTO `provinces` VALUES ('384', 'Huyện Mường Lát', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('385', 'Huyện Quan Hóa', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('386', 'Huyện Bá Thước', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('387', 'Huyện Quan Sơn', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('388', 'Huyện Lang Chánh', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('389', 'Huyện Ngọc Lặc', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('390', 'Huyện Cẩm Thủy', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('391', 'Huyện Thạch Thành', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('392', 'Huyện Hà Trung', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('393', 'Huyện Vĩnh Lộc', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('394', 'Huyện Yên Định', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('395', 'Huyện Thọ Xuân', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('396', 'Huyện Thường Xuân', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('397', 'Huyện Triệu Sơn', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('398', 'Huyện Thiệu Hóa', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('399', 'Huyện Hoằng Hóa', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('400', 'Huyện Hậu Lộc', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('401', 'Huyện Nga Sơn', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('402', 'Huyện Như Xuân', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('403', 'Huyện Như Thanh', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('404', 'Huyện Nông Cống', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('405', 'Huyện Đông Sơn', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('406', 'Huyện Quảng Xương', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('407', 'Huyện Tĩnh Gia', 'Huyện', '38');
// INSERT INTO `provinces` VALUES ('412', 'Thành phố Vinh', 'Thành phố', '40');
// INSERT INTO `provinces` VALUES ('413', 'Thị xã Cửa Lò', 'Thị xã', '40');
// INSERT INTO `provinces` VALUES ('414', 'Thị xã Thái Hoà', 'Thị xã', '40');
// INSERT INTO `provinces` VALUES ('415', 'Huyện Quế Phong', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('416', 'Huyện Quỳ Châu', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('417', 'Huyện Kỳ Sơn', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('418', 'Huyện Tương Dương', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('419', 'Huyện Nghĩa Đàn', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('420', 'Huyện Quỳ Hợp', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('421', 'Huyện Quỳnh Lưu', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('422', 'Huyện Con Cuông', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('423', 'Huyện Tân Kỳ', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('424', 'Huyện Anh Sơn', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('425', 'Huyện Diễn Châu', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('426', 'Huyện Yên Thành', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('427', 'Huyện Đô Lương', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('428', 'Huyện Thanh Chương', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('429', 'Huyện Nghi Lộc', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('430', 'Huyện Nam Đàn', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('431', 'Huyện Hưng Nguyên', 'Huyện', '40');
// INSERT INTO `provinces` VALUES ('432', 'Thị xã Hoàng Mai', 'Thị xã', '40');
// INSERT INTO `provinces` VALUES ('436', 'Thành phố Hà Tĩnh', 'Thành phố', '42');
// INSERT INTO `provinces` VALUES ('437', 'Thị xã Hồng Lĩnh', 'Thị xã', '42');
// INSERT INTO `provinces` VALUES ('439', 'Huyện Hương Sơn', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('440', 'Huyện Đức Thọ', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('441', 'Huyện Vũ Quang', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('442', 'Huyện Nghi Xuân', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('443', 'Huyện Can Lộc', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('444', 'Huyện Hương Khê', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('445', 'Huyện Thạch Hà', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('446', 'Huyện Cẩm Xuyên', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('447', 'Huyện Kỳ Anh', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('448', 'Huyện Lộc Hà', 'Huyện', '42');
// INSERT INTO `provinces` VALUES ('449', 'Thị xã Kỳ Anh', 'Thị xã', '42');
// INSERT INTO `provinces` VALUES ('450', 'Thành Phố Đồng Hới', 'Thành phố', '44');
// INSERT INTO `provinces` VALUES ('452', 'Huyện Minh Hóa', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('453', 'Huyện Tuyên Hóa', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('454', 'Huyện Quảng Trạch', 'Thị xã', '44');
// INSERT INTO `provinces` VALUES ('455', 'Huyện Bố Trạch', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('456', 'Huyện Quảng Ninh', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('457', 'Huyện Lệ Thủy', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('458', 'Thị xã Ba Đồn', 'Huyện', '44');
// INSERT INTO `provinces` VALUES ('461', 'Thành phố Đông Hà', 'Thành phố', '45');
// INSERT INTO `provinces` VALUES ('462', 'Thị xã Quảng Trị', 'Thị xã', '45');
// INSERT INTO `provinces` VALUES ('464', 'Huyện Vĩnh Linh', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('465', 'Huyện Hướng Hóa', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('466', 'Huyện Gio Linh', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('467', 'Huyện Đa Krông', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('468', 'Huyện Cam Lộ', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('469', 'Huyện Triệu Phong', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('470', 'Huyện Hải Lăng', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('471', 'Huyện Cồn Cỏ', 'Huyện', '45');
// INSERT INTO `provinces` VALUES ('474', 'Thành phố Huế', 'Thành phố', '46');
// INSERT INTO `provinces` VALUES ('476', 'Huyện Phong Điền', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('477', 'Huyện Quảng Điền', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('478', 'Huyện Phú Vang', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('479', 'Thị xã Hương Thủy', 'Thị xã', '46');
// INSERT INTO `provinces` VALUES ('480', 'Thị xã Hương Trà', 'Thị xã', '46');
// INSERT INTO `provinces` VALUES ('481', 'Huyện A Lưới', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('482', 'Huyện Phú Lộc', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('483', 'Huyện Nam Đông', 'Huyện', '46');
// INSERT INTO `provinces` VALUES ('490', 'Quận Liên Chiểu', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('491', 'Quận Thanh Khê', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('492', 'Quận Hải Châu', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('493', 'Quận Sơn Trà', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('494', 'Quận Ngũ Hành Sơn', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('495', 'Quận Cẩm Lệ', 'Quận', '48');
// INSERT INTO `provinces` VALUES ('497', 'Huyện Hòa Vang', 'Huyện', '48');
// INSERT INTO `provinces` VALUES ('498', 'Huyện Hoàng Sa', 'Huyện', '48');
// INSERT INTO `provinces` VALUES ('502', 'Thành phố Tam Kỳ', 'Thành phố', '49');
// INSERT INTO `provinces` VALUES ('503', 'Thành phố Hội An', 'Thành phố', '49');
// INSERT INTO `provinces` VALUES ('504', 'Huyện Tây Giang', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('505', 'Huyện Đông Giang', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('506', 'Huyện Đại Lộc', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('507', 'Thị xã Điện Bàn', 'Thị xã', '49');
// INSERT INTO `provinces` VALUES ('508', 'Huyện Duy Xuyên', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('509', 'Huyện Quế Sơn', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('510', 'Huyện Nam Giang', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('511', 'Huyện Phước Sơn', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('512', 'Huyện Hiệp Đức', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('513', 'Huyện Thăng Bình', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('514', 'Huyện Tiên Phước', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('515', 'Huyện Bắc Trà My', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('516', 'Huyện Nam Trà My', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('517', 'Huyện Núi Thành', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('518', 'Huyện Phú Ninh', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('519', 'Huyện Nông Sơn', 'Huyện', '49');
// INSERT INTO `provinces` VALUES ('522', 'Thành phố Quảng Ngãi', 'Thành phố', '51');
// INSERT INTO `provinces` VALUES ('524', 'Huyện Bình Sơn', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('525', 'Huyện Trà Bồng', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('526', 'Huyện Tây Trà', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('527', 'Huyện Sơn Tịnh', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('528', 'Huyện Tư Nghĩa', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('529', 'Huyện Sơn Hà', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('530', 'Huyện Sơn Tây', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('531', 'Huyện Minh Long', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('532', 'Huyện Nghĩa Hành', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('533', 'Huyện Mộ Đức', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('534', 'Huyện Đức Phổ', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('535', 'Huyện Ba Tơ', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('536', 'Huyện Lý Sơn', 'Huyện', '51');
// INSERT INTO `provinces` VALUES ('540', 'Thành phố Qui Nhơn', 'Thành phố', '52');
// INSERT INTO `provinces` VALUES ('542', 'Huyện An Lão', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('543', 'Huyện Hoài Nhơn', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('544', 'Huyện Hoài Ân', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('545', 'Huyện Phù Mỹ', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('546', 'Huyện Vĩnh Thạnh', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('547', 'Huyện Tây Sơn', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('548', 'Huyện Phù Cát', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('549', 'Thị xã An Nhơn', 'Thị xã', '52');
// INSERT INTO `provinces` VALUES ('550', 'Huyện Tuy Phước', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('551', 'Huyện Vân Canh', 'Huyện', '52');
// INSERT INTO `provinces` VALUES ('555', 'Thành phố Tuy Hoà', 'Thành phố', '54');
// INSERT INTO `provinces` VALUES ('557', 'Thị xã Sông Cầu', 'Thị xã', '54');
// INSERT INTO `provinces` VALUES ('558', 'Huyện Đồng Xuân', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('559', 'Huyện Tuy An', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('560', 'Huyện Sơn Hòa', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('561', 'Huyện Sông Hinh', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('562', 'Huyện Tây Hoà', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('563', 'Huyện Phú Hoà', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('564', 'Huyện Đông Hòa', 'Huyện', '54');
// INSERT INTO `provinces` VALUES ('568', 'Thành phố Nha Trang', 'Thành phố', '56');
// INSERT INTO `provinces` VALUES ('569', 'Thành phố Cam Ranh', 'Thành phố', '56');
// INSERT INTO `provinces` VALUES ('570', 'Huyện Cam Lâm', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('571', 'Huyện Vạn Ninh', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('572', 'Thị xã Ninh Hòa', 'Thị xã', '56');
// INSERT INTO `provinces` VALUES ('573', 'Huyện Khánh Vĩnh', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('574', 'Huyện Diên Khánh', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('575', 'Huyện Khánh Sơn', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('576', 'Huyện Trường Sa', 'Huyện', '56');
// INSERT INTO `provinces` VALUES ('582', 'Thành phố Phan Rang-Tháp Chàm', 'Thành phố', '58');
// INSERT INTO `provinces` VALUES ('584', 'Huyện Bác Ái', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('585', 'Huyện Ninh Sơn', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('586', 'Huyện Ninh Hải', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('587', 'Huyện Ninh Phước', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('588', 'Huyện Thuận Bắc', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('589', 'Huyện Thuận Nam', 'Huyện', '58');
// INSERT INTO `provinces` VALUES ('593', 'Thành phố Phan Thiết', 'Thành phố', '60');
// INSERT INTO `provinces` VALUES ('594', 'Thị xã La Gi', 'Thị xã', '60');
// INSERT INTO `provinces` VALUES ('595', 'Huyện Tuy Phong', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('596', 'Huyện Bắc Bình', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('597', 'Huyện Hàm Thuận Bắc', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('598', 'Huyện Hàm Thuận Nam', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('599', 'Huyện Tánh Linh', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('600', 'Huyện Đức Linh', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('601', 'Huyện Hàm Tân', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('602', 'Huyện Phú Quí', 'Huyện', '60');
// INSERT INTO `provinces` VALUES ('608', 'Thành phố Kon Tum', 'Thành phố', '62');
// INSERT INTO `provinces` VALUES ('610', 'Huyện Đắk Glei', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('611', 'Huyện Ngọc Hồi', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('612', 'Huyện Đắk Tô', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('613', 'Huyện Kon Plông', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('614', 'Huyện Kon Rẫy', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('615', 'Huyện Đắk Hà', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('616', 'Huyện Sa Thầy', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('617', 'Huyện Tu Mơ Rông', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('618', 'Huyện Ia H\' Drai', 'Huyện', '62');
// INSERT INTO `provinces` VALUES ('622', 'Thành phố Pleiku', 'Thành phố', '64');
// INSERT INTO `provinces` VALUES ('623', 'Thị xã An Khê', 'Thị xã', '64');
// INSERT INTO `provinces` VALUES ('624', 'Thị xã Ayun Pa', 'Thị xã', '64');
// INSERT INTO `provinces` VALUES ('625', 'Huyện KBang', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('626', 'Huyện Đăk Đoa', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('627', 'Huyện Chư Păh', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('628', 'Huyện Ia Grai', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('629', 'Huyện Mang Yang', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('630', 'Huyện Kông Chro', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('631', 'Huyện Đức Cơ', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('632', 'Huyện Chư Prông', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('633', 'Huyện Chư Sê', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('634', 'Huyện Đăk Pơ', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('635', 'Huyện Ia Pa', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('637', 'Huyện Krông Pa', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('638', 'Huyện Phú Thiện', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('639', 'Huyện Chư Pưh', 'Huyện', '64');
// INSERT INTO `provinces` VALUES ('643', 'Thành phố Buôn Ma Thuột', 'Thành phố', '66');
// INSERT INTO `provinces` VALUES ('644', 'Thị Xã Buôn Hồ', 'Thị xã', '66');
// INSERT INTO `provinces` VALUES ('645', 'Huyện Ea H\'leo', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('646', 'Huyện Ea Súp', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('647', 'Huyện Buôn Đôn', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('648', 'Huyện Cư M\'gar', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('649', 'Huyện Krông Búk', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('650', 'Huyện Krông Năng', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('651', 'Huyện Ea Kar', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('652', 'Huyện M\'Đrắk', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('653', 'Huyện Krông Bông', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('654', 'Huyện Krông Pắc', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('655', 'Huyện Krông A Na', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('656', 'Huyện Lắk', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('657', 'Huyện Cư Kuin', 'Huyện', '66');
// INSERT INTO `provinces` VALUES ('660', 'Thị xã Gia Nghĩa', 'Thị xã', '67');
// INSERT INTO `provinces` VALUES ('661', 'Huyện Đăk Glong', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('662', 'Huyện Cư Jút', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('663', 'Huyện Đắk Mil', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('664', 'Huyện Krông Nô', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('665', 'Huyện Đắk Song', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('666', 'Huyện Đắk R\'Lấp', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('667', 'Huyện Tuy Đức', 'Huyện', '67');
// INSERT INTO `provinces` VALUES ('672', 'Thành phố Đà Lạt', 'Thành phố', '68');
// INSERT INTO `provinces` VALUES ('673', 'Thành phố Bảo Lộc', 'Thành phố', '68');
// INSERT INTO `provinces` VALUES ('674', 'Huyện Đam Rông', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('675', 'Huyện Lạc Dương', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('676', 'Huyện Lâm Hà', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('677', 'Huyện Đơn Dương', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('678', 'Huyện Đức Trọng', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('679', 'Huyện Di Linh', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('680', 'Huyện Bảo Lâm', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('681', 'Huyện Đạ Huoai', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('682', 'Huyện Đạ Tẻh', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('683', 'Huyện Cát Tiên', 'Huyện', '68');
// INSERT INTO `provinces` VALUES ('688', 'Thị xã Phước Long', 'Thị xã', '70');
// INSERT INTO `provinces` VALUES ('689', 'Thị xã Đồng Xoài', 'Thị xã', '70');
// INSERT INTO `provinces` VALUES ('690', 'Thị xã Bình Long', 'Thị xã', '70');
// INSERT INTO `provinces` VALUES ('691', 'Huyện Bù Gia Mập', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('692', 'Huyện Lộc Ninh', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('693', 'Huyện Bù Đốp', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('694', 'Huyện Hớn Quản', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('695', 'Huyện Đồng Phú', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('696', 'Huyện Bù Đăng', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('697', 'Huyện Chơn Thành', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('698', 'Huyện Phú Riềng', 'Huyện', '70');
// INSERT INTO `provinces` VALUES ('703', 'Thành phố Tây Ninh', 'Thành phố', '72');
// INSERT INTO `provinces` VALUES ('705', 'Huyện Tân Biên', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('706', 'Huyện Tân Châu', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('707', 'Huyện Dương Minh Châu', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('708', 'Huyện Châu Thành', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('709', 'Huyện Hòa Thành', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('710', 'Huyện Gò Dầu', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('711', 'Huyện Bến Cầu', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('712', 'Huyện Trảng Bàng', 'Huyện', '72');
// INSERT INTO `provinces` VALUES ('718', 'Thành phố Thủ Dầu Một', 'Thành phố', '74');
// INSERT INTO `provinces` VALUES ('719', 'Huyện Bàu Bàng', 'Huyện', '74');
// INSERT INTO `provinces` VALUES ('720', 'Huyện Dầu Tiếng', 'Huyện', '74');
// INSERT INTO `provinces` VALUES ('721', 'Thị xã Bến Cát', 'Thị xã', '74');
// INSERT INTO `provinces` VALUES ('722', 'Huyện Phú Giáo', 'Huyện', '74');
// INSERT INTO `provinces` VALUES ('723', 'Thị xã Tân Uyên', 'Thị xã', '74');
// INSERT INTO `provinces` VALUES ('724', 'Thị xã Dĩ An', 'Thị xã', '74');
// INSERT INTO `provinces` VALUES ('725', 'Thị xã Thuận An', 'Thị xã', '74');
// INSERT INTO `provinces` VALUES ('726', 'Huyện Bắc Tân Uyên', 'Huyện', '74');
// INSERT INTO `provinces` VALUES ('731', 'Thành phố Biên Hòa', 'Thành phố', '75');
// INSERT INTO `provinces` VALUES ('732', 'Thị xã Long Khánh', 'Thị xã', '75');
// INSERT INTO `provinces` VALUES ('734', 'Huyện Tân Phú', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('735', 'Huyện Vĩnh Cửu', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('736', 'Huyện Định Quán', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('737', 'Huyện Trảng Bom', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('738', 'Huyện Thống Nhất', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('739', 'Huyện Cẩm Mỹ', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('740', 'Huyện Long Thành', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('741', 'Huyện Xuân Lộc', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('742', 'Huyện Nhơn Trạch', 'Huyện', '75');
// INSERT INTO `provinces` VALUES ('747', 'Thành phố Vũng Tàu', 'Thành phố', '77');
// INSERT INTO `provinces` VALUES ('748', 'Thành phố Bà Rịa', 'Thành phố', '77');
// INSERT INTO `provinces` VALUES ('750', 'Huyện Châu Đức', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('751', 'Huyện Xuyên Mộc', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('752', 'Huyện Long Điền', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('753', 'Huyện Đất Đỏ', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('754', 'Huyện Tân Thành', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('755', 'Huyện Côn Đảo', 'Huyện', '77');
// INSERT INTO `provinces` VALUES ('760', 'Quận 1', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('761', 'Quận 12', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('762', 'Quận Thủ Đức', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('763', 'Quận 9', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('764', 'Quận Gò Vấp', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('765', 'Quận Bình Thạnh', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('766', 'Quận Tân Bình', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('767', 'Quận Tân Phú', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('768', 'Quận Phú Nhuận', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('769', 'Quận 2', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('770', 'Quận 3', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('771', 'Quận 10', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('772', 'Quận 11', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('773', 'Quận 4', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('774', 'Quận 5', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('775', 'Quận 6', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('776', 'Quận 8', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('777', 'Quận Bình Tân', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('778', 'Quận 7', 'Quận', '79');
// INSERT INTO `provinces` VALUES ('783', 'Huyện Củ Chi', 'Huyện', '79');
// INSERT INTO `provinces` VALUES ('784', 'Huyện Hóc Môn', 'Huyện', '79');
// INSERT INTO `provinces` VALUES ('785', 'Huyện Bình Chánh', 'Huyện', '79');
// INSERT INTO `provinces` VALUES ('786', 'Huyện Nhà Bè', 'Huyện', '79');
// INSERT INTO `provinces` VALUES ('787', 'Huyện Cần Giờ', 'Huyện', '79');
// INSERT INTO `provinces` VALUES ('794', 'Thành phố Tân An', 'Thành phố', '80');
// INSERT INTO `provinces` VALUES ('795', 'Thị xã Kiến Tường', 'Thị xã', '80');
// INSERT INTO `provinces` VALUES ('796', 'Huyện Tân Hưng', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('797', 'Huyện Vĩnh Hưng', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('798', 'Huyện Mộc Hóa', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('799', 'Huyện Tân Thạnh', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('800', 'Huyện Thạnh Hóa', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('801', 'Huyện Đức Huệ', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('802', 'Huyện Đức Hòa', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('803', 'Huyện Bến Lức', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('804', 'Huyện Thủ Thừa', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('805', 'Huyện Tân Trụ', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('806', 'Huyện Cần Đước', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('807', 'Huyện Cần Giuộc', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('808', 'Huyện Châu Thành', 'Huyện', '80');
// INSERT INTO `provinces` VALUES ('815', 'Thành phố Mỹ Tho', 'Thành phố', '82');
// INSERT INTO `provinces` VALUES ('816', 'Thị xã Gò Công', 'Thị xã', '82');
// INSERT INTO `provinces` VALUES ('817', 'Thị xã Cai Lậy', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('818', 'Huyện Tân Phước', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('819', 'Huyện Cái Bè', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('820', 'Huyện Cai Lậy', 'Thị xã', '82');
// INSERT INTO `provinces` VALUES ('821', 'Huyện Châu Thành', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('822', 'Huyện Chợ Gạo', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('823', 'Huyện Gò Công Tây', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('824', 'Huyện Gò Công Đông', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('825', 'Huyện Tân Phú Đông', 'Huyện', '82');
// INSERT INTO `provinces` VALUES ('829', 'Thành phố Bến Tre', 'Thành phố', '83');
// INSERT INTO `provinces` VALUES ('831', 'Huyện Châu Thành', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('832', 'Huyện Chợ Lách', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('833', 'Huyện Mỏ Cày Nam', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('834', 'Huyện Giồng Trôm', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('835', 'Huyện Bình Đại', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('836', 'Huyện Ba Tri', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('837', 'Huyện Thạnh Phú', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('838', 'Huyện Mỏ Cày Bắc', 'Huyện', '83');
// INSERT INTO `provinces` VALUES ('842', 'Thành phố Trà Vinh', 'Thành phố', '84');
// INSERT INTO `provinces` VALUES ('844', 'Huyện Càng Long', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('845', 'Huyện Cầu Kè', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('846', 'Huyện Tiểu Cần', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('847', 'Huyện Châu Thành', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('848', 'Huyện Cầu Ngang', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('849', 'Huyện Trà Cú', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('850', 'Huyện Duyên Hải', 'Huyện', '84');
// INSERT INTO `provinces` VALUES ('851', 'Thị xã Duyên Hải', 'Thị xã', '84');
// INSERT INTO `provinces` VALUES ('855', 'Thành phố Vĩnh Long', 'Thành phố', '86');
// INSERT INTO `provinces` VALUES ('857', 'Huyện Long Hồ', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('858', 'Huyện Mang Thít', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('859', 'Huyện  Vũng Liêm', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('860', 'Huyện Tam Bình', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('861', 'Thị xã Bình Minh', 'Thị xã', '86');
// INSERT INTO `provinces` VALUES ('862', 'Huyện Trà Ôn', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('863', 'Huyện Bình Tân', 'Huyện', '86');
// INSERT INTO `provinces` VALUES ('866', 'Thành phố Cao Lãnh', 'Thành phố', '87');
// INSERT INTO `provinces` VALUES ('867', 'Thành phố Sa Đéc', 'Thành phố', '87');
// INSERT INTO `provinces` VALUES ('868', 'Thị xã Hồng Ngự', 'Thị xã', '87');
// INSERT INTO `provinces` VALUES ('869', 'Huyện Tân Hồng', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('870', 'Huyện Hồng Ngự', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('871', 'Huyện Tam Nông', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('872', 'Huyện Tháp Mười', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('873', 'Huyện Cao Lãnh', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('874', 'Huyện Thanh Bình', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('875', 'Huyện Lấp Vò', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('876', 'Huyện Lai Vung', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('877', 'Huyện Châu Thành', 'Huyện', '87');
// INSERT INTO `provinces` VALUES ('883', 'Thành phố Long Xuyên', 'Thành phố', '89');
// INSERT INTO `provinces` VALUES ('884', 'Thành phố Châu Đốc', 'Thành phố', '89');
// INSERT INTO `provinces` VALUES ('886', 'Huyện An Phú', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('887', 'Thị xã Tân Châu', 'Thị xã', '89');
// INSERT INTO `provinces` VALUES ('888', 'Huyện Phú Tân', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('889', 'Huyện Châu Phú', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('890', 'Huyện Tịnh Biên', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('891', 'Huyện Tri Tôn', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('892', 'Huyện Châu Thành', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('893', 'Huyện Chợ Mới', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('894', 'Huyện Thoại Sơn', 'Huyện', '89');
// INSERT INTO `provinces` VALUES ('899', 'Thành phố Rạch Giá', 'Thành phố', '91');
// INSERT INTO `provinces` VALUES ('900', 'Thị xã Hà Tiên', 'Thị xã', '91');
// INSERT INTO `provinces` VALUES ('902', 'Huyện Kiên Lương', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('903', 'Huyện Hòn Đất', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('904', 'Huyện Tân Hiệp', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('905', 'Huyện Châu Thành', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('906', 'Huyện Giồng Riềng', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('907', 'Huyện Gò Quao', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('908', 'Huyện An Biên', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('909', 'Huyện An Minh', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('910', 'Huyện Vĩnh Thuận', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('911', 'Huyện Phú Quốc', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('912', 'Huyện Kiên Hải', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('913', 'Huyện U Minh Thượng', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('914', 'Huyện Giang Thành', 'Huyện', '91');
// INSERT INTO `provinces` VALUES ('916', 'Quận Ninh Kiều', 'Quận', '92');
// INSERT INTO `provinces` VALUES ('917', 'Quận Ô Môn', 'Quận', '92');
// INSERT INTO `provinces` VALUES ('918', 'Quận Bình Thuỷ', 'Quận', '92');
// INSERT INTO `provinces` VALUES ('919', 'Quận Cái Răng', 'Quận', '92');
// INSERT INTO `provinces` VALUES ('923', 'Quận Thốt Nốt', 'Quận', '92');
// INSERT INTO `provinces` VALUES ('924', 'Huyện Vĩnh Thạnh', 'Huyện', '92');
// INSERT INTO `provinces` VALUES ('925', 'Huyện Cờ Đỏ', 'Huyện', '92');
// INSERT INTO `provinces` VALUES ('926', 'Huyện Phong Điền', 'Huyện', '92');
// INSERT INTO `provinces` VALUES ('927', 'Huyện Thới Lai', 'Huyện', '92');
// INSERT INTO `provinces` VALUES ('930', 'Thành phố Vị Thanh', 'Thành phố', '93');
// INSERT INTO `provinces` VALUES ('931', 'Thị xã Ngã Bảy', 'Thị xã', '93');
// INSERT INTO `provinces` VALUES ('932', 'Huyện Châu Thành A', 'Huyện', '93');
// INSERT INTO `provinces` VALUES ('933', 'Huyện Châu Thành', 'Huyện', '93');
// INSERT INTO `provinces` VALUES ('934', 'Huyện Phụng Hiệp', 'Huyện', '93');
// INSERT INTO `provinces` VALUES ('935', 'Huyện Vị Thuỷ', 'Huyện', '93');
// INSERT INTO `provinces` VALUES ('936', 'Huyện Long Mỹ', 'Huyện', '93');
// INSERT INTO `provinces` VALUES ('937', 'Thị xã Long Mỹ', 'Thị xã', '93');
// INSERT INTO `provinces` VALUES ('941', 'Thành phố Sóc Trăng', 'Thành phố', '94');
// INSERT INTO `provinces` VALUES ('942', 'Huyện Châu Thành', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('943', 'Huyện Kế Sách', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('944', 'Huyện Mỹ Tú', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('945', 'Huyện Cù Lao Dung', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('946', 'Huyện Long Phú', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('947', 'Huyện Mỹ Xuyên', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('948', 'Thị xã Ngã Năm', 'Thị xã', '94');
// INSERT INTO `provinces` VALUES ('949', 'Huyện Thạnh Trị', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('950', 'Thị xã Vĩnh Châu', 'Thị xã', '94');
// INSERT INTO `provinces` VALUES ('951', 'Huyện Trần Đề', 'Huyện', '94');
// INSERT INTO `provinces` VALUES ('954', 'Thành phố Bạc Liêu', 'Thành phố', '95');
// INSERT INTO `provinces` VALUES ('956', 'Huyện Hồng Dân', 'Huyện', '95');
// INSERT INTO `provinces` VALUES ('957', 'Huyện Phước Long', 'Huyện', '95');
// INSERT INTO `provinces` VALUES ('958', 'Huyện Vĩnh Lợi', 'Huyện', '95');
// INSERT INTO `provinces` VALUES ('959', 'Thị xã Giá Rai', 'Thị xã', '95');
// INSERT INTO `provinces` VALUES ('960', 'Huyện Đông Hải', 'Huyện', '95');
// INSERT INTO `provinces` VALUES ('961', 'Huyện Hoà Bình', 'Huyện', '95');
// INSERT INTO `provinces` VALUES ('964', 'Thành phố Cà Mau', 'Thành phố', '96');
// INSERT INTO `provinces` VALUES ('966', 'Huyện U Minh', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('967', 'Huyện Thới Bình', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('968', 'Huyện Trần Văn Thời', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('969', 'Huyện Cái Nước', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('970', 'Huyện Đầm Dơi', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('971', 'Huyện Năm Căn', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('972', 'Huyện Phú Tân', 'Huyện', '96');
// INSERT INTO `provinces` VALUES ('973', 'Huyện Ngọc Hiển', 'Huyện', '96');
